export const FETCH_ACTIVITIES_REQUEST = "FETCH_ACTIVITIES_REQUEST";
export const FETCH_ACTIVITIES_SUCCESS = "FETCH_ACTIVITIES_SUCCESS";
export const FETCH_ACTIVITIES_FAILURE = "FETCH_ACTIVITIES_FAILURE";
export const SET_ACTIVITY_DATA = "SET_ACTIVITY_DATA";
export const UPDATE_ACTIVITY_DATA = "UPDATE_ACTIVITY_DATA";
