export const FETCH_PROJECTS_REQUEST = "FETCH_PROJECTS_REQUEST";
export const FETCH_PROJECTS_SUCCESS = "FETCH_PROJECTS_SUCCESS";
export const FETCH_PROJECTS_FAILURE = "FETCH_PROJECTS_FAILURE";
export const SET_PROJECT_DATA = "SET_PROJECT_DATA";
export const UPDATE_PROJECT_DATA = "UPDATE_PROJECT_DATA";
export const SET_LAST_CREATED_PROJECT = "SET_LAST_CREATED_PROJECT";
