export const FETCH_LABEL_REQUEST = "FETCH_LABEL_REQUEST";
export const FETCH_LABEL_SUCCESS = "FETCH_LABEL_SUCCESS";
export const FETCH_LABEL_FAILURE = "FETCH_LABEL_FAILURE";
export const SET_LABEL_DATA = "SET_LABEL_DATA";
