export const FETCH_LABELS_REQUEST = "FETCH_LABELS_REQUEST";
export const FETCH_LABELS_SUCCESS = "FETCH_LABELS_SUCCESS";
export const FETCH_LABELS_FAILURE = "FETCH_LABELS_FAILURE";
export const SET_LABEL_DATA = "SET_LABEL_DATA";
