export const FETCH_FILTERS_REQUEST = "FETCH_FILTERS_REQUEST";
export const FETCH_FILTERS_SUCCESS = "FETCH_FILTERS_SUCCESS";
export const FETCH_FILTERS_FAILURE = "FETCH_FILTERS_FAILURE";
export const SET_FILTER_DATA = "SET_FILTER_DATA";
