export const FETCH_SUBTASK_REQUEST = "FETCH_SUBTASK_REQUEST";
export const FETCH_SUBTASK_SUCCESS = "FETCH_SUBTASK_SUCCESS";
export const FETCH_SUBTASK_FAILURE = "FETCH_SUBTASK_FAILURE";
export const SET_SUBTASK_DATA = "SET_SUBTASK_DATA";
