export const FETCH_SUBTASKS_REQUEST = "FETCH_SUBTASKS_REQUEST";
export const FETCH_SUBTASKS_SUCCESS = "FETCH_SUBTASKS_SUCCESS";
export const FETCH_SUBTASKS_FAILURE = "FETCH_SUBTASKS_FAILURE";
export const SET_SUBTASK_DATA = "SET_SUBTASK_DATA";
export const UPDATE_SUBTASK_DATA = "UPDATE_SUBTASK_DATA";
